#   P H A N T O M S

###  P H A N T O M S ###
/gate/world/daughters/name                      phantom
/gate/world/daughters/insert                    cylinder
/gate/phantom/setMaterial                	    Polyethylene
#/gate/phantom/vis/forceWireframe
#/gate/phantom/vis/setColor                      grey
#/gate/phantom/vis/setVisible                    1

/gate/phantom/geometry/setRmin                  0 mm
/gate/phantom/geometry/setRmax                  25 mm
/gate/phantom/geometry/setHeight                120 mm
/gate/phantom/geometry/setPhiStart              0 deg
/gate/phantom/geometry/setDeltaPhi              360 deg
/gate/phantom/placement/setRotationAxis               1 0 0
/gate/phantom/placement/setRotationAngle              90 deg

/gate/phantom/placement/setTranslation          -1 -2 3 mm

#/gate/phantom/attachPhantomSD
/gate/geometry/rebuild
#/vis/viewer/update


### S O U R C E     D E F I N I T I O N ###

/gate/phantom/daughters/name                      Source1
/gate/phantom/daughters/insert                    cylinder
/gate/Source1/setMaterial                Water
#/gate/Source1/vis/forceWireframe
#/gate/Source1/vis/setColor               cyan
#/gate/Source1/vis/setVisible             1
/gate/Source1/geometry/setHeight        100 mm
/gate/Source1/geometry/setRmin           0 mm
/gate/Source1/geometry/setRmax           6 mm
/gate/Source1/geometry/setPhiStart       0 deg
/gate/Source1/geometry/setDeltaPhi       360 deg
/gate/Source1/placement/setTranslation   0 0 0 mm

#/gate/Source1/attachPhantomSD
/gate/geometry/rebuild
#/vis/viewer/update


/gate/geometry/rebuild

#/vis/viewer/update


#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize


### S O U R C E    D E F I N I T I O N ###

# F A S T   P R O D U C T I O N   M O D U L E   F O R   F - 1 8   I S O T O P E S
# S O U R C E
/gate/source/addSource twogamma
/gate/source/twogamma/setActivity {Act} MBq
/gate/source/twogamma/setType backtoback

# POSITION
/gate/source/twogamma/gps/centre 0. 0. 0. cm

# PARTICLE
/gate/source/twogamma/gps/particle gamma
/gate/source/twogamma/gps/energytype Mono
/gate/source/twogamma/gps/monoenergy 0.511 MeV

# TYPE = Volume or Surface or Point

/gate/source/twogamma/gps/type Volume
/gate/source/twogamma/gps/shape Cylinder
/gate/source/twogamma/gps/radius 6 mm
/gate/source/twogamma/gps/halfz  50 mm
/gate/source/twogamma/gps/angtype iso
/gate/source/twogamma/gps/centre 0.0 0.0 0.0 mm

# SET THE ANGULAR DISTRIBUTION OF EMISSION
/gate/source/twogamma/gps/angtype iso

# SET MIN AND MAX EMISSION ANGLES
/gate/source/twogamma/gps/mintheta 0. deg
/gate/source/twogamma/gps/maxtheta 180. deg
/gate/source/twogamma/gps/minphi    0. deg
/gate/source/twogamma/gps/maxphi 360. deg

/gate/source/twogamma/attachTo     Source1

/gate/source/list


#-------------------oooooOOOOO00000OOOOOooooo---------------------#
#                                                                 #
#                   D E F I N I T I O N   O F                     #
#                Y O U R   O U T P U T   F I L E                  #
#                                                                 #
#-------------------oooooOOOOO00000OOOOOooooo---------------------#

#=====================================================
#  D A T A   O U T P U T   
#=====================================================

/gate/random/setEngineSeed 123456789


#/gate/output/root/enable
#/gate/output/root/setFileName                    output/Test_
#/gate/output/root/setRootHitFlag            0
#/gate/output/root/setRootSinglesFlag        1
#/gate/output/root/setRootCoincidencesFlag   1
#/gate/output/root/setRootNtupleFlag         0

/gate/output/ascii/enable
/gate/output/ascii/setFileName                    output/Automated/{type}_250mm_{Act}MBq_
/gate/output/ascii/setOutFileHitsFlag           0
/gate/output/ascii/setOutFileSinglesFlag        0
/gate/output/ascii/setOutFileEWindowFlag	    0
/gate/output/ascii/setOutFileCoincidencesFlag   1
#/gate/output/ascii/setSingleMask 0 1 0 0 0 0 1 1 0 1 1 1 1 1 0 0 0 0 0 0
/gate/output/ascii/setCoincidenceMask 0 0 0 0 0 0 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 
#                               run evnt src srcX srcY srcZ V1-V6 tms Erg sinX sinY sinZ cptPhan cptDect rgPhan rgDetec Name1 Name2

