[paths]
directory = "access_seed12349"
results = "access_seed12349/results"
outputs = "access_seed12349/outputs"
script = "access_seed12349/access_script.py"
setup = "access_seed12349/access_setup.toml"
epochs = "access_seed12349/epochs_pop100.csv"
epochs_scaled = "access_seed12349/epochs_pop100_scaled.csv"
history = "access_seed12349/history_pop100.csv"
history_scaled = "access_seed12349/history_pop100_scaled.csv"

[setup]
scaling = [ 1.2000000000000002, 4.0,]
population = 100
target = 0.1
seed = 12349

[setup.parameters.value]
dt1 = 1.5
tres = 15.0

[setup.parameters.min]
dt1 = 0.0
tres = 10.0

[setup.parameters.max]
dt1 = 3.0
tres = 20.0

[setup.parameters.sigma]
dt1 = 1.2000000000000002
tres = 4.0

[setup.parameters_scaled.value]
dt1 = 1.2499999999999998
tres = 3.75

[setup.parameters_scaled.min]
dt1 = 0.0
tres = 2.5

[setup.parameters_scaled.max]
dt1 = 2.4999999999999996
tres = 5.0

[setup.parameters_scaled.sigma]
dt1 = 1.0
tres = 1.0
