#-------------------oooooOOOOO00000OOOOOooooo---------------------#
#                                                                 #
#  D E F I N I T I O N   O F   Y O U R   A C Q U I S I T I O N    #
#  D I G I T I Z E R   &   C O I N C I D E N C E   S H O R T E R  #
#                                                                 #
#-------------------oooooOOOOO00000OOOOOooooo---------------------#

#	A D D E R
/gate/digitizer/Singles/insert adder

/gate/distributions/name energy_distrib
/gate/distributions/insert Gaussian
/gate/distributions/energy_distrib/setMean 511 keV
/gate/distributions/energy_distrib/setSigma 1 keV

/gate/distributions/name dt_distrib
/gate/distributions/insert Exponential
/gate/distributions/dt_distrib/setLambda 1.97 us

/gate/digitizer/Singles/insert noise
/gate/digitizer/Singles/noise/setDeltaTDistribution dt_distrib
/gate/digitizer/Singles/noise/setEnergyDistribution energy_distrib

#       R E A D O U T
#/gate/digitizer/Singles/insert readout
#/gate/digitizer/Singles/readout/setDepth	2
/gate/digitizer/Singles/insert readout
/gate/digitizer/Singles/readout/setPolicy TakeEnergyCentroid
/gate/digitizer/Singles/readout/setDepth 4

#	T I M E   R E S O L U T I O N
/gate/digitizer/Singles/insert timeResolution
/gate/digitizer/Singles/timeResolution/setTimeResolution 13.72 ns

#	P I L E U P
/gate/digitizer/Singles/insert pileup
/gate/digitizer/Singles/pileup/setDepth 2
/gate/digitizer/Singles/pileup/setPileup 637.4 ns

#      E N E R G Y   B L U R R I N G
/gate/digitizer/Singles/insert blurring
/gate/digitizer/Singles/blurring/setResolution 0.5
/gate/digitizer/Singles/blurring/setEnergyOfReference 511. keV

#       E N E R G Y   C U T
/gate/digitizer/Singles/insert                              thresholder
/gate/digitizer/Singles/thresholder/setThreshold            324 keV
/gate/digitizer/Singles/insert                              upholder
/gate/digitizer/Singles/upholder/setUphold                  2000 keV

#       D E A D    T I M E 
/gate/digitizer/Singles/insert deadtime
/gate/digitizer/Singles/deadtime/setDeadTime 6.63 us
/gate/digitizer/Singles/deadtime/setMode nonparalysable
/gate/digitizer/Singles/deadtime/chooseDTVolume block

#       E N E R G Y     W I N D O W
/gate/digitizer/name                                EWindow
/gate/digitizer/insert                              singleChain
/gate/digitizer/EWindow/setInputName                Singles

# 50 % energy window
/gate/digitizer/EWindow/insert                      thresholder
/gate/digitizer/EWindow/thresholder/setThreshold    400 keV
/gate/digitizer/EWindow/insert                      upholder
/gate/digitizer/EWindow/upholder/setUphold          700 keV


#	    C O I N C I D E N C E    S O R T E R 
/gate/digitizer/Coincidences/setInputName           EWindow
/gate/digitizer/Coincidences/setWindow              12 ns
/gate/digitizer/Coincidences/MultiplesPolicy	    takeAllGoods
/gate/digitizer/Coincidences/minSectorDifference    1
/gate/digitizer/Coincidences/describe

/gate/digitizer/name delayed
/gate/digitizer/insert coincidenceSorter
/gate/digitizer/delayed/setInputName EWindow
/gate/digitizer/delayed/setOffset 256 ns
/gate/digitizer/delayed/setWindow 12 ns
/gate/digitizer/delayed/MultiplesPolicy        takeAllGoods
/gate/digitizer/delayed/minSectorDifference 1
/gate/digitizer/delayed/describe

/gate/digitizer/name finalCoinc
/gate/digitizer/insert coincidenceChain
/gate/digitizer/finalCoinc/addInputName delayed
/gate/digitizer/finalCoinc/addInputName Coincidences
#/gate/digitizer/finalCoinc/usePriority False
/gate/digitizer/finalCoinc/describe

